variables:
  global_variable: 'Global value'

pool:
  name: Azure Pipelines
  demands: npm

jobs:
  job:
  variables:
    glocal_variable: 'local value'
	
  steps:
    - bash:
	    echo $(global_variable)

	- task: Npm@1
	  displayName: 'npm install'
	  inputs:
		verbose: false

	- task: Npm@1
	  displayName: 'npm custom'
	  inputs:
		command: custom
		verbose: false
		customCommand: 'run start:dev &'
	  enabled: false

	- script: |
	   node -v
	   npm run start:dev &
	  displayName: 'Command Line Script'

	- task: Docker@2
	  displayName: build
	  inputs:
		command: build

